# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: demo_app
  username: Ryan
  password: kampbill2h
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
